// -*- C++ -*-
//
// generated by wxGlade 1.1.0pre on Tue Aug 15 19:51:27 2023
//
// Example for compiling a single file project under Linux using g++:
//  g++ MyApp.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp
//
// Example for compiling a multi file project under Linux using g++:
//  g++ main.cpp $(wx-config --libs) $(wx-config --cxxflags) -o MyApp Dialog1.cpp Frame1.cpp
//

#ifndef JOURNYMAINFRAME_H
#define JOURNYMAINFRAME_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/calctrl.h>
#include <wx/listctrl.h>
// end wxGlade

// begin wxGlade: ::extracode
// end wxGlade


class JournyMainFrame: public wxFrame {
public:
    // begin wxGlade: JournyMainFrame::ids
    // end wxGlade

    JournyMainFrame(wxWindow* parent, wxWindowID id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:

protected:
    // begin wxGlade: JournyMainFrame::attributes
    wxMenuBar* frame_menubar;
    wxListCtrl* list_ctrl_1;
    wxCalendarCtrl* calendar_ctrl_1;
    wxPanel* panel_1;
    // end wxGlade
}; // wxGlade: end class


#endif // JOURNYMAINFRAME_H
